version: 2
jobs:
    build_demo:
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v2-dependencies-react-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd components
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - components/node_modules
                  key: v2-dependencies-react-{{ checksum "yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      yarn lint
            - run:
                  name: Test
                  command: |
                      yarn test
            # - run:
            #       name: Build Demo
            #       command: |
            #           yarn build

workflows:
    version: 2
    react_library:
        jobs:
            - build_demo
