version: 2.1
orbs:
    codecov: codecov/codecov@1.1.3
jobs:
    build_demo:
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v2-dependencies-react-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - /node_modules
                  key: v2-dependencies-react-{{ checksum "yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      yarn lint
            - run:
                  name: Unit Test
                  command: |
                      yarn test --coverage --watchAll=false
            - run:
                  name: Build Demo
                  command: |
                      yarn build
            - persist_to_workspace:
                root: .
                paths:
                    - coverage

    coverage_report:
        working_directory: ~/react-showcase-demo
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - attach_workspace:
                at: .
            - codecov/upload:
                file: './coverage/clover.xml'
                token: e071b5d8-7127-4351-8acd-54f56d36a39c

workflows:
    version: 2
    react_library:
        jobs:
            - build_demo
            - coverage_report:
                   requires:
                        - build_demo
                #    filters:
                #         branches:
                #             only:
                #                 - master
